// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: test1_project

#include "ui.h"

void led1_toggle_func(lv_event_t * e)
{
	// Your code here
}

void led_toggle_func(lv_event_t * e)
{
	// Your code here
}
