// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: test1_project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_btnPage1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_btnPage1, 148);
lv_obj_set_height( ui_btnPage1, 50);
lv_obj_set_x( ui_btnPage1, 2 );
lv_obj_set_y( ui_btnPage1, -38 );
lv_obj_set_align( ui_btnPage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPage1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_btnPage1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Sayfa 1");

ui_btnPage2 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_btnPage2, 148);
lv_obj_set_height( ui_btnPage2, 50);
lv_obj_set_x( ui_btnPage2, 1 );
lv_obj_set_y( ui_btnPage2, 40 );
lv_obj_set_align( ui_btnPage2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnPage2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnPage2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_btnPage2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Sayfa 2");

lv_obj_add_event_cb(ui_btnPage1, ui_event_btnPage1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnPage2, ui_event_btnPage2, LV_EVENT_ALL, NULL);

}
