// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: test1_project

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel1, 194);
lv_obj_set_height( ui_Panel1, 50);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -73 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -52 );
lv_obj_set_y( ui_Label3, 1 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"LED 1:");

ui_swLed1 = lv_switch_create(ui_Panel1);
lv_obj_set_width( ui_swLed1, 50);
lv_obj_set_height( ui_swLed1, 25);
lv_obj_set_x( ui_swLed1, 58 );
lv_obj_set_y( ui_swLed1, 0 );
lv_obj_set_align( ui_swLed1, LV_ALIGN_CENTER );


ui_btnMain1 = lv_btn_create(ui_Screen2);
lv_obj_set_width( ui_btnMain1, 148);
lv_obj_set_height( ui_btnMain1, 50);
lv_obj_set_x( ui_btnMain1, 0 );
lv_obj_set_y( ui_btnMain1, 82 );
lv_obj_set_align( ui_btnMain1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnMain1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnMain1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_btnMain1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Ana Sayfa");

ui_Panel2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2, 194);
lv_obj_set_height( ui_Panel2, 50);
lv_obj_set_x( ui_Panel2, -2 );
lv_obj_set_y( ui_Panel2, -4 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -52 );
lv_obj_set_y( ui_Label4, 1 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"LED 2:");

ui_swLed2 = lv_switch_create(ui_Panel2);
lv_obj_set_width( ui_swLed2, 50);
lv_obj_set_height( ui_swLed2, 25);
lv_obj_set_x( ui_swLed2, 58 );
lv_obj_set_y( ui_swLed2, 0 );
lv_obj_set_align( ui_swLed2, LV_ALIGN_CENTER );


lv_obj_add_event_cb(ui_swLed1, ui_event_swLed1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_btnMain1, ui_event_btnMain1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_swLed2, ui_event_swLed2, LV_EVENT_ALL, NULL);

}
