// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: test1_project

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel3, 257);
lv_obj_set_height( ui_Panel3, 69);
lv_obj_set_x( ui_Panel3, -2 );
lv_obj_set_y( ui_Panel3, -72 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sliderLed3 = lv_slider_create(ui_Panel3);
lv_obj_set_width( ui_sliderLed3, 217);
lv_obj_set_height( ui_sliderLed3, 10);
lv_obj_set_x( ui_sliderLed3, 4 );
lv_obj_set_y( ui_sliderLed3, 16 );
lv_obj_set_align( ui_sliderLed3, LV_ALIGN_CENTER );


ui_txtSliderVal = lv_label_create(ui_Panel3);
lv_obj_set_width( ui_txtSliderVal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_txtSliderVal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_txtSliderVal, 43 );
lv_obj_set_y( ui_txtSliderVal, -15 );
lv_obj_set_align( ui_txtSliderVal, LV_ALIGN_CENTER );
lv_label_set_text(ui_txtSliderVal,"%0");

ui_btnMain2 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_btnMain2, 148);
lv_obj_set_height( ui_btnMain2, 50);
lv_obj_set_x( ui_btnMain2, 0 );
lv_obj_set_y( ui_btnMain2, 82 );
lv_obj_set_align( ui_btnMain2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_btnMain2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_btnMain2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_label20 = lv_label_create(ui_btnMain2);
lv_obj_set_width( ui_label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_label20,"Ana Sayfa");

ui_Panel4 = lv_obj_create(ui_Screen3);
lv_obj_set_width( ui_Panel4, 257);
lv_obj_set_height( ui_Panel4, 69);
lv_obj_set_x( ui_Panel4, -2 );
lv_obj_set_y( ui_Panel4, 9 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txtPgVal1 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_txtPgVal1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_txtPgVal1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_txtPgVal1, 43 );
lv_obj_set_y( ui_txtPgVal1, 19 );
lv_obj_set_align( ui_txtPgVal1, LV_ALIGN_CENTER );
lv_label_set_text(ui_txtPgVal1,"%25");

ui_pgLed1 = lv_bar_create(ui_Panel4);
lv_bar_set_value(ui_pgLed1,25,LV_ANIM_OFF);
lv_obj_set_width( ui_pgLed1, 201);
lv_obj_set_height( ui_pgLed1, 10);
lv_obj_set_x( ui_pgLed1, 1 );
lv_obj_set_y( ui_pgLed1, -12 );
lv_obj_set_align( ui_pgLed1, LV_ALIGN_CENTER );

ui_Label1 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -53 );
lv_obj_set_y( ui_Label1, -86 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"LED 3:");

ui_Label7 = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -49 );
lv_obj_set_y( ui_Label7, 27 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"POT:");

lv_obj_add_event_cb(ui_btnMain2, ui_event_btnMain2, LV_EVENT_ALL, NULL);

}
