// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: test1_project

#include "ui.h"

extern uint8_t led1_stat, led2_stat;

void led1_toggle_func(lv_event_t * e)
{
	// Your code here
	led1_stat = lv_obj_has_state(e->target, LV_STATE_CHECKED);
}

void led2_toggle_func(lv_event_t * e)
{
	// Your code here
	led2_stat = lv_obj_has_state(e->target, LV_STATE_CHECKED);
}
